CREATE TABLE [dbo].[LOGS]
(
	[ID] BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    [LEVEL] NVARCHAR(10) NOT NULL, 
    [MESSAGE] NVARCHAR(MAX) NOT NULL, 
    [STACK_TRACE] NVARCHAR(MAX) NULL, 
    [FULL_EXCEPTION] NVARCHAR(MAX) NULL, 
    [CREATED_ON_UTC] DATETIME NOT NULL
)
