CREATE TABLE [dbo].[POSTS]
(
	[ID] BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[USER_POST] NVARCHAR(2000) NOT NULL,
	[USER_NAME] NVARCHAR(300) NOT NULL,
	[USER_MEDIA] VARCHAR(100) NOT NULL,
	[USER_IP] VARCHAR(45) NOT NULL,
	[USER_COUNTRY] VARCHAR(2),
	[USER_BROWSER] VARCHAR(100),
	[USER_OS] VARCHAR(100),
	[CREATED_ON_UTC] DATETIME2 NOT NULL
)
